name: Android Build

on:
  push:
    branches: [ "YuukiPS_V1" ]
  pull_request:
    branches: [ "YuukiPS_V1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Compile RA
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease
        find . -iname "*.apk" -exec l -l "{}" \;
        ls -l app
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
    - uses: actions/upload-artifact@v4
      with:
        name: Launcher-android-${{ steps.slug.outputs.sha8 }}
        path: |
          app/build/outputs/apk/release/app-release-unsigned.apk
